markdown: redcarpet
highlighter: pygments
permalink: /:title/

sass:
  style: :compressed

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - package.json
  - node_modules
